image: golang:1.11

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/gopkg.in
    - node_modules

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind
  - mongo

stages:
  - test

before_script:
  - export DOCKER_REPOSITORY="mendersoftware/workflows"
  - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
  - export SERVICE_IMAGE=$DOCKER_REPOSITORY:$DOCKER_TAG
  - export COMMIT_TAG="$CI_COMMIT_REF_SLUG"_"$CI_COMMIT_SHA"

test:static:
  stage: test
  dependencies: []
  services: []
  script:
    # Install cyclomatic dependency analysis tool
    - go get -u github.com/fzipp/gocyclo
    - curl -sL https://deb.nodesource.com/setup_11.x | bash -
    - apt-get -qq update
    - apt-get install -qy --allow-unauthenticated python3-pip nodejs liblzma-dev
    - pip3 install pyyaml
    - npm install -g swagger-cli
    # Get our own Swagger verifier
    - wget https://raw.githubusercontent.com/mendersoftware/autodocs/master/verify_docs.py
    - mkdir -p /go/src/github.com/mendersoftware /go/src/_/builds
    - cp -r $CI_PROJECT_DIR /go/src/github.com/mendersoftware/workflows
    - ln -s /go/src/github.com/mendersoftware /go/src/_/builds/mendersoftware
    - cd /go/src/github.com/mendersoftware/workflows
    # Test if code was formatted with 'go fmt'
    # Command will format code and return modified files
    # fail if any have been modified.
    - if [ -n "$(go fmt)" ]; then echo 'Code is not formatted with "go fmt"'; false; fi
    # Perform static code analysys
    - go vet `go list ./... | grep -v vendor`
    # Fail builds when the cyclomatic complexity reaches 20 or more
    - gocyclo -over 20 `find . -iname '*.go' | grep -v 'vendor' | grep -v '_test.go'`
    # Verify that the Swagger docs are valid
    - swagger-cli validate docs/*.yml
    # Verify that the Swagger docs follow the autodeployment requirements
    - python3 verify_docs.py `find docs -name "*.yml"`

test:unit:
  stage: test
  dependencies: []
  script:
    # Install code coverage tooling
    - go get -u github.com/axw/gocov/gocov
    - go get -u golang.org/x/tools/cmd/cover

    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin

    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    - echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list
    - apt-get -qq update && apt-get install -qy --allow-unauthenticated mongodb-org-server=3.6.11  liblzma-dev
    - mkdir -p /go/src/github.com/mendersoftware /go/src/_/builds
    - cp -r $CI_PROJECT_DIR /go/src/github.com/mendersoftware/workflows
    - ln -s /go/src/github.com/mendersoftware /go/src/_/builds/mendersoftware
    - cd /go/src/github.com/mendersoftware/workflows
    - go list ./... | grep -v vendor | xargs -n1 -I {} -P 4 go test -v -covermode=atomic -coverprofile=../../../{}/coverage.txt {} || exit $? ;
    - mkdir -p tests/unit-coverage && find . -name 'coverage.txt' -exec cp --parents {} ./tests/unit-coverage \;
    - tar -cvf $CI_PROJECT_DIR/unit-coverage.tar tests/unit-coverage
  artifacts:
    expire_in: 2w
    paths:
      - unit-coverage.tar
